# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

ignored = ["github.com/redhat-nfvpe/telemetry-consumers"]

[[constraint]]
  branch = "master"
  name = "github.com/MakeNowJust/heredoc"

[[constraint]]
  name = "github.com/olivere/elastic"
  version = "6.1.24"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[constraint]]
  name = "github.com/satori/go.uuid"
  branch = "master"

[[constraint]]
  revision = "b25d21e6779a011e972a5f00e433e2034b793da1"
  name = "qpid.apache.org"

[[constraint]]
  revision = "606bd390f38f050824c77208d6715ed59e3692ac"
  name = "collectd.org"


[prune]
  go-tests = true
  unused-packages = true
